import { 
  collection, 
  doc, 
  setDoc, 
  getDoc, 
  getDocs,
  updateDoc,
  serverTimestamp 
} from 'firebase/firestore'
import { db } from './config'

// Save user data and survey responses
export const saveUserData = async (userId, userData, surveyData) => {
  try {
    const userRef = doc(db, 'users', userId)
    
    const userDocument = {
      email: userData.email,
      fullName: userData.fullName || userData.displayName || '',
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
      preferences: {
        goals: surveyData?.q2 || [],
        academicLevel: surveyData?.q1 || '',
        subjects: surveyData?.q3 || '',
        studyHours: surveyData?.q4 || '',
        preferredTime: surveyData?.q5 || '',
        stressLevel: surveyData?.q6 || null,
        sleepHours: surveyData?.q7 || '',
        biggestChallenge: surveyData?.q8 || '',
        notifications: surveyData?.q9 || []
      },
      plan: null, // Will be generated by AI later
      habits: {
        waterCount: 0,
        steps: 0,
        sleepHours: 0
      },
      schedule: {
        sessions: []
      },
      tasks: {
        tasks: []
      },
      streak: 0,
      lastActive: serverTimestamp()
    }
    
    await setDoc(userRef, userDocument, { merge: true })
    
    return {
      success: true,
      error: null
    }
  } catch (error) {
    console.error('Error saving user data:', error)
    return {
      success: false,
      error: error.message
    }
  }
}

// Get user data
export const getUserData = async (userId) => {
  try {
    const userRef = doc(db, 'users', userId)
    const userSnap = await getDoc(userRef)
    
    if (userSnap.exists()) {
      return {
        data: userSnap.data(),
        error: null
      }
    } else {
      return {
        data: null,
        error: 'User document does not exist'
      }
    }
  } catch (error) {
    console.error('Error getting user data:', error)
    return {
      data: null,
      error: error.message
    }
  }
}

// Update user data
export const updateUserData = async (userId, updates) => {
  try {
    const userRef = doc(db, 'users', userId)
    await updateDoc(userRef, {
      ...updates,
      updatedAt: serverTimestamp()
    })
    
    return {
      success: true,
      error: null
    }
  } catch (error) {
    console.error('Error updating user data:', error)
    return {
      success: false,
      error: error.message
    }
  }
}

// Update user habits
export const updateHabits = async (userId, habits) => {
  try {
    const userRef = doc(db, 'users', userId)
    await updateDoc(userRef, {
      'habits': habits,
      updatedAt: serverTimestamp()
    })
    
    return {
      success: true,
      error: null
    }
  } catch (error) {
    console.error('Error updating habits:', error)
    return {
      success: false,
      error: error.message
    }
  }
}

// Update user tasks
export const updateTasks = async (userId, tasks) => {
  try {
    const userRef = doc(db, 'users', userId)
    await updateDoc(userRef, {
      'tasks.tasks': tasks,
      updatedAt: serverTimestamp()
    })
    
    return {
      success: true,
      error: null
    }
  } catch (error) {
    console.error('Error updating tasks:', error)
    return {
      success: false,
      error: error.message
    }
  }
}

// Update user schedule
export const updateSchedule = async (userId, schedule) => {
  try {
    const userRef = doc(db, 'users', userId)
    await updateDoc(userRef, {
      'schedule.sessions': schedule,
      updatedAt: serverTimestamp()
    })
    
    return {
      success: true,
      error: null
    }
  } catch (error) {
    console.error('Error updating schedule:', error)
    return {
      success: false,
      error: error.message
    }
  }
}

// Save chat messages
export const saveChatMessages = async (userId, messages) => {
  try {
    const userRef = doc(db, 'users', userId)
    await updateDoc(userRef, {
      chatMessages: messages,
      updatedAt: serverTimestamp()
    })
    
    return {
      success: true,
      error: null
    }
  } catch (error) {
    console.error('Error saving chat messages:', error)
    return {
      success: false,
      error: error.message
    }
  }
}

// Get chat messages
export const getChatMessages = async (userId) => {
  try {
    const userRef = doc(db, 'users', userId)
    const userSnap = await getDoc(userRef)
    
    if (userSnap.exists()) {
      const userData = userSnap.data()
      return {
        messages: userData.chatMessages || [],
        error: null
      }
    } else {
      return {
        messages: [],
        error: null
      }
    }
  } catch (error) {
    console.error('Error getting chat messages:', error)
    return {
      messages: [],
      error: error.message
    }
  }
}

// Get all users for leaderboard
export const getAllUsers = async () => {
  try {
    const usersRef = collection(db, 'users')
    const usersSnap = await getDocs(usersRef)
    
    const users = []
    usersSnap.forEach((doc) => {
      const userData = doc.data()
      users.push({
        id: doc.id,
        ...userData
      })
    })
    
    return {
      users,
      error: null
    }
  } catch (error) {
    console.error('Error getting all users:', error)
    return {
      users: [],
      error: error.message
    }
  }
}

